# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 04:54
from __future__ import unicode_literals

from django.db import migrations


def cria_cidades(apps, schema_editor):
    Localizacao = apps.get_model("medcal", "Localizacao")
    Cidade = apps.get_model('medcal', 'Cidade')
    cidades = Localizacao.objects.values_list('cidade').distinct()
    # Each record is returned as a tuple, there is just one field. So
    # we have to get the first element.
    for cidade_nome in cidades:
        cidade = Cidade.objects.create(nome=cidade_nome[0])
        cidade.save()


def atualiza_chave_estrangeira_cidade(apps, schema_editor):
    Localizacao = apps.get_model("medcal", "Localizacao")
    Cidade = apps.get_model('medcal', 'Cidade')
    for obj_cidade in Cidade.objects.all():
        local_filter = Localizacao.objects.filter(cidade=obj_cidade.nome)
        local_filter.update(cidade_fk=obj_cidade)


class Migration(migrations.Migration):

    dependencies = [
        ('medcal', '0002_auto_20161221_0254'),
    ]

    operations = [
        migrations.RunPython(cria_cidades),
        migrations.RunPython(atualiza_chave_estrangeira_cidade),
    ]
