# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcal', '0003_auto_20161221_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacao',
            name='cidade',
        ),
    ]
