# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField()),
            ],
            options={
                'db_table': 'AGENDA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ESPECIALIDADE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_localicacao_cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=45, null=True)),
                ('num', models.CharField(blank=True, max_length=5, null=True)),
                ('compl', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'LOCALIZACAO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medcal.Especialidade')),
            ],
            options={
                'db_table': 'MEDICO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'PACIENTE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='localizacao',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medcal.Medico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcal.Medico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medcal.Paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together=set([('id', 'medico', 'datahora')]),
        ),
    ]
