INSERT INTO `medcal_especialidade` VALUES (1,'Acupuntura'),(2,'Alergia e Imunologia'),(3,'Anestesiologia'),(4,'Angiologia'),(5,'Cancerologia'),(6,'Cardiologia'),(7,'Cirurgia Cardiovascular'),(8,'Cirurgia da Mão'),(9,'Cirurgia de cabeça e pescoço'),(10,'Cirurgia do Aparelho Digestivo'),(11,'Cirurgia Geral'),(12,'Cirurgia Pediátrica'),(13,'Cirurgia Plástica'),(14,'Cirurgia Torácica'),(15,'Cirurgia Vascular'),(16,'Clínica Médica'),(17,'Coloproctologia'),(18,'Dermatologia'),(19,'Endocrinologia e Metabologia'),(20,'Endoscopia'),(21,'Gastroenterologia'),(22,'Genética médica'),(23,'Geriatria'),(24,'Ginecologia e obstetrícia'),(25,'Hematologia e Hemoterapia'),(26,'Homeopatia'),(27,'Infectologia'),(28,'Mastologia'),(29,'Medicina de Família e Comunidade'),(30,'Medicina do Trabalho'),(31,'Medicina do Tráfego'),(32,'Medicina Esportiva'),(33,'Medicina Física e Reabilitação'),(34,'Medicina Intensiva'),(35,'Medicina Legal e Perícia Médica'),(36,'Medicina Nuclear'),(37,'Medicina Preventiva e Social'),(38,'Nefrologia'),(39,'Neurocirurgia'),(40,'Neurologia'),(41,'Nutrologia'),(42,'Obstetrícia'),(43,'Oftalmologia'),(44,'Ortopedia e Traumatologia'),(45,'Otorrinolaringologia'),(46,'Patologia'),(47,'Patologia Clínica/Medicina laboratorial'),(48,'Pediatria'),(49,'Pneumologia'),(50,'Psiquiatria'),(51,'Radiologia e Diagnóstico por Imagem'),(52,'Radioterapia'),(53,'Reumatologia'),(54,'Urologia');

INSERT INTO `medcal_medico` VALUES (1,'Amauri Jose Zuotoski',1),(2,'Beatriz Maria Matte Peplow',1),(3,'Braulio Augusto Correa Melo',1),(4,'Carlos Henrique Bertozzi Staut',1),(5,'Carlos Makoto Moriya',1);

INSERT INTO `medcal_localizacao` VALUES (1,'80020905','R MARECHAL DEODORO','51','SALA 805 A B','CENTRO','Curitiba','PR',1),(2,'80520270','R DOM ALBERTO GONCALVES','919','','BOM RETIRO','Curitiba','PR',2),(3,'80020320','R MARECHAL DEODORO','51','SALA 1106 A','CENTRO','Curitiba','PR',3),(4,'80010200','R JOAO NEGRAO','731','23 ANDAR','CENTRO','Curitiba','PR',4),(5,'80045135','R PROFESSOR BRANDAO','50','','ALTO DA XV','Curitiba','PR',5);

INSERT INTO `medcal_paciente`(`id`,`nome`) VALUES (1, 'Bernaldo Feigundes');

INSERT INTO `medcal_agenda`(`id`,`datahora`, `medico_id`, `paciente_id`) VALUES (1, '2017-03-12 17:23:00', 1, 1);
